<a href="https://colab.research.google.com/github/Samuel-538/FML-lab-Work/blob/main/lab_1_3_03_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
print(type(a),a.shape,a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [ ]:
a = np.zeros((2,2)) 
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
c = np.full((2,2), 78) 
print(c)

[[78 78]
 [78 78]]


In [ ]:
d = np.eye(2)        
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
e = np.random.random((2,2)) #as the name'random' suggests it creates a array of random elements
print(e)

[[0.69927303 0.48829588]
 [0.29219132 0.24730003]]


In [ ]:
#row slicing is a view of the same data but in a modified way rows:columns
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a[:2,1:3]
print(b)

[[2 3]
 [5 6]]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(a)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
row_r1=a[:2]
row_r2=a[:,:2]
print(row_r1)
print(row_r2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]
 [7 8]]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])     #elementwise sum similarly all the other other arithmetic functions performs the elementwise operations 
print(np.add(a,b)) #.sqrt() also performs elementwise


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a@b)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
